  name: CI-CD
  on:
    push:
      branches: ["main", "development", "homologation"]
    workflow_dispatch:
  jobs:
    CI:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Obter código"
        - run: echo "Executar docker build"
        - run: echo "Enviar imagem para o dockerhub"
    CD:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Obter código"
        - run: echo "Configurar o kuberconfig"
        - run: echo "Executar o apply"
